// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzgibnwhvivaddjkguuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Z2libndodml2YWRkamtndXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMDUxOTIsImV4cCI6MjA0OTg4MTE5Mn0.PaYGKl4yfGpg6EFZBO-tZUJ2wBbbLmVSVSIbgzA0Mr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);